// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package params

// The `openclaw` plugin's OWN CUE schema — the typed plugin_input for the
// `openclaw` check verb, which probes a running OpenClaw 2.0 gateway: liveness /
// readiness / startup via the /healthz /readyz /startupz HTTP probe endpoints, and
// gateway state (status, models, channels, version) via the in-venue `openclaw` CLI.
//
// SELF-CONTAINED by contract: it references NO base def, so it compiles standalone
// (both `cue exp gengotypes` and the host's load-gate compile) AND splices onto the
// base as `base ++ plugin`.
//
// Single source, used two ways:
//  1. GENERATE ../params/cue_types_gen.go via `cue exp gengotypes`, so the provider
//     decodes plugin_input into a TYPED struct rather than a hand-parsed map.
//  2. VALIDATE authored input AT RUNTIME — served over Describe, spliced by the host,
//     and every authored `openclaw:` step's plugin_input checked against #OpenclawInput.
type OpenclawInput struct {
	// method — the operation (also the scalar-sugar primary, so `openclaw: health`
	// desugars to {method: "health"}).
	//
	// HTTP probe methods (health/ready/startup) are issued from the charly HOST against
	// the resolved gateway endpoint; CLI methods (status/models/channels/version) run
	// inside the venue where the `openclaw` binary is installed. All are read-only —
	// there are no mutating methods in this first cut.
	Method string `json:"method"`

	// port — the gateway port to probe. Default 18789 (the openclaw candy's published
	// port, relayed from the loopback-bound gateway by socat).
	Port int64 `json:"port,omitempty"`

	// timeout — the HTTP probe timeout. Default 10s.
	Timeout string `json:"timeout,omitempty"`

	// json_path — a dotted path into the JSON response; when set, the verb's stdout is
	// the value at that path rather than the whole document, so a `stdout:` matcher can
	// assert one field without pattern-matching a blob.
	JSONPath string `json:"json_path,omitempty"`
}
